export const LOGIN = "LOGIN";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const SESSION_STORE = "SESSION_STORE";
export const SESSION_STORE_TO_NULL = "SESSION_STORE_TO_NULL";
export const DELETE_ZEROTH_SESSION = "DELETE_ZEROTH_SESSION";
export const DELETE_NTH_SESSION = "DELETE_NTH_SESSION";
export const SET_NEW_SESSION_INFO = "SET_NEW_SESSION_INFO";
export const SET_GLOBAL_USER_AGENT = "SET_GLOBAL_USER_AGENT";
export const ACCEPT_SESSION = "ACCEPT_SESSION";
export const REJECT_SESSION = "REJECT_SESSION";
export const SESSION_DUPLICATE_ADD = "SESSION_INFO_DUPLICATE_ADD";
export const SESSION_INFO_DUPLICATE_ADD = "SESSION_DUPLICATE_ADD";
export const SESSION_DUPLICATE_DELETE = "SESSION_DUPLICATE_DELETE";
export const HIDE = "HIDE";
export const ONGOING = "ONGOING";
export const POPUP = "POPUP";
export const NAV_HEADER = "NAV_HEADER";
export const NAV_SUBHEADER = "NAV_SUBHEADER";
export const USER_REGISTERED = "USER_REGISTERED";
export const USER_DATABASE = "USER_DATABASE";
export const GET_MY_CONTACT = "GET_MY_CONTACT";
export const INITIAL_MY_CONTACT = "INITIAL_MY_CONTACT";
export const GET_CENTRAL_CONTACT = "GET_CENTRAL_CONTACT";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const GET_REMOTE_CONTACT = "GET_REMOTE_CONTACT";
export const GET_CALL_LOG = "GET_CALL_LOG";
export const COLLAPSE_DASHBOARD = "COLLAPSE_DASHBOARD";

export const CALL_START_TIME = "CALL_START_TIME";
export const CALL_TYPE = "CALL_TYPE";
export const CALLEE_ID = "CALLEE_ID";
export const CALLEE_NAME = "CALLEE_NAME";
export const CALL_NUMBER = "CALL_NUMBER";

export const DEMO_CALL = "DEMO_CALL";
export const DELETE_DEMO_CALL = "DELETE_DEMO_CALL";
export const DEMO_STATE = "DEMO_STATE";
export const MISSED_STATUS = "MISSED_STATUS";

export const COLLAPSE_SIDEBAR = "COLLAPSE_SIDEBAR";
export const ADD_CONFERENCE = "ADD_CONFERENCE";
export const REMOVE_CONFERENCE = "REMOVE_CONFERENCE";

// db update for call log
export const DB_LOG_UPDATE = "DB_LOG_UPDATE";

// export const DISPLAY_ONGOING = 'DISPLAY_ONGOING';

//efax
export const GET_ALL_EFAX = "GET_ALL_EFAX";
export const SEND_EFAX = "SEND_EFAX";

//small screen
export const SINGLE_SCREEN = "SINGLE_SCREEN";
export const SCREEN_SIZE_CHANGE = "SCREEN_SIZE_CHANGE";
//sms
export const NOTIFICATION_ARRAY = "NOTIFICATION_ARRAY";
export const NOTIFICATION_REMOVE = "NOTIFICATION_REMOVE";
export const GROUP_NOTIFICATION = "GROUP_NOTIFICATION";

// login change
export const LOGIN_CHANGE = "LOGIN_CHANGE";
export const STATUS_CHANGE_NUMBER = "STATUS_CHANGE_NUMBER";
export const DYNAMIC_DATA_CHANGE = "DYNAMIC_DATA_CHANGE";

//useragent

export const REPEATED_NUMBER = "REPEATED_NUMBER";
export const SHOW_ONGOING = "SHOW_ONGOING";
